---
- hosts: 192.168.6.122,192.168.6.123
  remote_user: root
  vars: 
    script_home: /package

  tasks:

  # 检查环境变量是否存在jdk的配置，并定义变量result/bi
  - name: check jdk variable 
    shell: cat /etc/profile
    register: result

  # 复制jdk文件到目标主机
  - name: copy jdk remote hosts
    copy: src=/package/java_jdk.tar.gz dest=/bubidata/server/

  # 解压jdk包到目标路径
  - name: tar xvf java_jdk.tar.gz
    shell: chdir=/bubidata/server tar zxf java_jdk.tar.gz

  # 修改/etc/profile配置文件
  - name: java_profile config
    shell: /bin/echo {{ item }} >> /etc/profile && source /etc/profile
    when: result.stdout.find('JAVA_HOME') == -1
    with_items:
      - export JAVA_HOME=/bubidata/server/java
      - export CLASS_PATH=.:\$JAVA_HOME/lib/dt.jar:\$JAVA_HOME/lib/tools.jar
      - export PATH=\$JAVA_HOME/bin:\$PATH

  # 应用配置文件生效
  - name: source profile
    shell: source /etc/profile
    