---
- hosts: "{ host_ip }"
  remote_user: root
  vars: 
    script_home: "/package"
    jdk_package_name: "java_jdk.tar.gz"
    localhost_host_path: "/bubidata/server"

  tasks:
  - file:
      path: "{{ localhost_host_path }}"
      state: directory 

  - name: 检查环境变量是否存在jdk的配置
    shell: cat /etc/profile
    register: result

  - name: 复制jdk文件到目标主机
    copy: src={{ script_home }}/{{ jdk_package_name }} dest={{ localhost_host_path }}

  - name: 解压jdk包到目标路径
    shell: chdir={{ localhost_host_path }} tar zxf {{ jdk_package_name }}

  - name: 修改/etc/profile配置文件
    shell: /bin/echo {{ item }} >> /etc/profile && source /etc/profile
    when: result.stdout.find('JAVA_HOME') == -1
    with_items:
      - export JAVA_HOME={{ localhost_host_path }}/java
      - export CLASS_PATH=.:\$JAVA_HOME/lib/dt.jar:\$JAVA_HOME/lib/tools.jar
      - export PATH=\$JAVA_HOME/bin:\$PATH

  - name: 应用配置文件生效
    shell: source /etc/profile
    