---
- hosts: ""
  remote_user: root
  vars: 
    script_home: "/package"
    jdk_package_name: "java_jdk.tar.gz"
    localhost_host_path: "/bubidata/server"

  tasks:
  - file:
      path: "{{ localhost_host_path }}"
      state: directory 

  - name: check disk
    shell: df -hP|awk 'NR>1 && int($5) > 10'|awk '/success/{ip=$1;next}{print ip,$0}'
    register: result_disk
  - debug: msg="{{result_disk.stdout_lines}}"

  - name: check port
    shell: "ss -ntl"
    register: result_port
  - debug: msg="{{result_port.stdout_lines}}" 

  - name: check memroy
    shell: "free -m"
    register: result_memory
  - debug: msg="{{result_memory.stdout_lines}}"
  
  - name: check cpu
    shell: "iostat -c"
    register: result_cpu
  - debug: msg="{{result_cpu.stdout_lines}}"

  - name: 安装解压命令unzip包
    yum: name="unzip.x86_64" state=installed

  - name: 检查环境变量是否存在jdk的配置
    shell: cat /etc/profile
    register: result

  - name: 复制jdk文件到目标主机
    copy: src={{ script_home }}/{{ jdk_package_name }} dest={{ localhost_host_path }}
    
  - name: 解压jdk包到目标路径
    shell: chdir={{ localhost_host_path }} tar zxf {{ jdk_package_name }}

  - name: 修改/etc/profile配置文件
    shell: /bin/echo {{ item }} >> /etc/profile && source /etc/profile
    when: result.stdout.find('JAVA_HOME') == -1
    with_items:
      - export JAVA_HOME={{ localhost_host_path }}/java
      - export CLASS_PATH=.:\$JAVA_HOME/lib/dt.jar:\$JAVA_HOME/lib/tools.jar
      - export PATH=\$JAVA_HOME/bin:\$PATH

  - debug: msg="java version "1.8.0_71""
