---
- hosts: "{{ host_ip }}"
  remote_user: "root"
  tasks:
    - name: shell
      shell: echo "123"
      register: echo
    - debug: msg="{{ echo.stdout }}"

    - name: ls -lrt
      shell: ls -lrt /tmp/

