---
- hosts: 192.168.5.100
  remote_user: root
  vars:
    src_host_path: /home/jekins/.jenkins/workspace/test-yinuojr-discovery/target
    localhost_host_path: /data/backup/yinuojr-discovery/target
    project_name: yinuojr-discovery
    src_host_ip: 192.168.2.40
    dst_host_ip: 192.168.5.100

  tasks:
    - name: 创建变量对应的目录
      file: path={{ item }} state=directory
      with_items:
        - "{{ src_host_path }}"
        - "{{ localhost_host_path }}"
        - "{{ src_host_ip }}"
        - "{{ project_name }}"

    - name: 远程拷贝更新包到本地机器
      command: "scp root@{{ src_host_ip }}:{{ src_host_path }}/{{ project_name }}.zip {{ localhost_host_path }}"

    - name: 生成本地包MD5码临时文件
      shell: "ssh root@{{ dst_host_ip }} md5sum {{ localhost_host_path }}/{{ project_name }}.zip >/tmp/md5sum_local_tmp.txt"
    
    - name: 生成Jenkins源头包MD5码临时文件
      shell: "ssh root@{{ src_host_ip }} md5sum {{ src_host_path }}/{{ project_name }}.zip >/tmp/md5sum_jenkins_tmp.txt"
    
    - name: 生成本地包MD5码比对文件
      shell: cat /tmp/md5sum_local_tmp.txt |awk '{print $1}' >/tmp/md5sum_local_ops.txt
      register: md5sum_dest
    
    - name: 生成Jenkins源头包MD5码比对文件
      shell: cat /tmp/md5sum_jenkins_tmp.txt |awk '{print $1}' >/tmp/md5sum_jenkins_ops.txt
      register: md5sum_src

    - name: 校验源头包和本地包的MD5码是否一致，一致输出md5sum right,不一致输出md5sum error
      shell: 'if [ "$md5sum_src" = "$md5sum_dest" ];then echo "md5sum right";else echo "md5sum error";fi'
      register: result    
    - debug: msg="{{result.stdout}}"
