---
- hosts: 192.168.5.100
  remote_user: root
  vars:
    src_host_path: /home/jekins/.jenkins/workspace/test-yinuojr-discovery/target
    localhost_host_path: /data/backup/yinuojr-discovery/target
    project_name: yinuojr-discovery
    src_host_ip: 192.168.2.40
    dst_host_ip: 192.168.5.100

  tasks:
    - name: 创建变量对应的目录
      file: path={{ item }} state=directory
      with_items:
        - "{{ src_host_path }}"
        - "{{ localhost_host_path }}"
        - "{{ src_host_ip }}"
        - "{{ project_name }}"

    - name: 远程拷贝更新包到本地机器
      command: "sshpass -pbubi scp root@{{ src_host_ip }}:{{ src_host_path }}/{{ project_name }}.zip {{ localhost_host_path }}"

    - name: 校验生成本地包的MD5码
      command: "ssh root@{{ dst_host_ip }} 'ls -lrt {{ localhost_host_path }}/{{ project_name }}.zip;md5sum {{ localhost_host_path }}/{{ project_name }}.zip'"
      register: check_scp_package
    - debug: msg={{check_scp_package.stdout_lines}}
  
    - name: 校验生成Jenkins源头包的MD5码
      command: "ssh root@{{ src_host_ip }} 'ls -lrt {{ src_host_path }}/{{ project_name }}.zip;md5sum {{ src_host_path }}/{{ project_name }}.zip'"
      register: check_src_package
    - debug: msg={{check_src_package.stdout_lines}}