---
- hosts: 192.168.6.123
  remote_user: root
  vars:
    src_host_path: /home/jekins/.jenkins/workspace/test-yinuojr-discovery/target
    dst_host_path: /data/backup/yinuojr-discovery/target
    project_data_path: /bubidata/server/data
    project_backup_path: /data/backup
    project_name: yinuojr-discovery
    service_run_port: 11009
    src_host_ip: 192.168.2.40
    dst_host_ip: 192.168.6.123
    random_number: "{{ 10000 | random }}"
    
    
  tasks:
    - name: create directory
      file: path={{ item }} state=directory
      with_items:
        - "{{ src_host_path }}"
        - "{{ dst_host_path }}"
        - "{{ project_backup_path }}"
        - "{{ project_name }}"
        - "{{ project_data_path }}"

    - wait_for: path={{ src_host_path }} state=present
    - wait_for: path={{ dst_host_path }} state=present
    - wait_for: path={{ project_backup_path }} state=present
    - wait_for: path={{ project_name }} state=present
    - wait_for: path={{ project_data_path }} state=present

    - name: check yinuojr_discovery service status
      shell: "ps -ef|grep discovery|grep -v grep |awk '{print $2}'"
      register: check_out_discovery
    - debug: msg="{{check_out_discovery.stdout_lines}}"

    - name: stop yinuojr_discovery service
      shell: source /etc/profile && cd {{ project_data_path }}/{{ project_name }}/bin && ./launch stop

    - name: check yinuojr_discovery service stop 
      wait_for: port={{ service_run_port }} delay=3 state=stopped timeout=10

    - name: backup current yinuojr_discovery package 
      shell: tar czvf {{ project_backup_path }}/{{ project_name}}.tar.gz {{ project_data_path }}/{{ project_name }}

    - name: delete current package
      shell: cd {{ project_data_path }} && rm -rf {{ project_name }} && rm -rf {{ project_name }}.zip
    - wait_for: path={{ project_data_path }}/{{ project_name }} state=absent
    - wait_for: path={{ project_data_path }}/{{ project_name }}.zip state=absent

    - name: copy yinuojr_discovery package to dst host and unzip 
      unarchive: src={{ dst_host_path }}/{{ project_name }}.zip dest={{ project_data_path }}

    - name: start yinuojr_discovery service
      shell: source /etc/profile && cd {{ project_data_path }}/{{ project_name }}/bin && ./launch start

    - name: check yinuojr_discovery service port status
      wait_for: port={{ service_run_port }} delay=5 state=started

    - name: yinuojr_discovery service start
      shell: echo "Start Successful !!!"
